const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94728866985"
const SESSION_ID = "PRABATH-MD~w7dzBTZB#GpEux21u6rCUf-ybpHbe21AsGJNkH3bPdAyvCI6o4ks"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
